I=imread('02.jpg');
Ig = I(:, :, 2);
Ir = I(:, :, 1);
Ib = I(:, :, 3);
%Ie = edge((histeq(Ir)), 'canny',0.6);
se = strel('disk',4);
Ith = imtophat(I,se);
Ic = imadjust(Ith(:,:,1));
Ican = edge(Ic,'canny', 0.3);
C  = (I + imtophat(I,se)) - imbothat(I,se);
figure;
imshow(C);
figure;
imshow(Ican);
% imshow(histeq(Ir));